export const keys = [
  // Function row
  { text: "esc", type: "C", w: "w-[82px]" ,pos: "left"},
  { text: "F1", type: "B" },
  { text: "F2", type: "B" },
  { text: "F3", type: "B" },
  { text: "F4", type: "B" },
  { text: "F5", type: "B" },
  { text: "F6", type: "B" },
  { text: "F7", type: "B" },
  { text: "F8", type: "B" },
  { text: "F9", type: "B" },
  { text: "F10", type: "B" },
  { text: "F11", type: "B" },
  { text: "F12", type: "B" },
  { type: "power" },

  // Number row
  { text: "`", image: "~", type: "B" },
  { text: "1", image: "!", type: "B" },
  { text: "2", image: "@", type: "B" },
  { text: "3", image: "#", type: "B" },
  { text: "4", image: "$", type: "B" },
  { text: "5", image: "%", type: "B" },
  { text: "6", image: "^", type: "B" },
  { text: "7", image: "&", type: "B" },
  { text: "8", image: "*", type: "B" },
  { text: "9", image: "(", type: "B" },
  { text: "0", image: ")", type: "B" },
  { text: "-", image: "_", type: "B" },
  { text: "=", image: "+", type: "B" },
  { text: "delete", type: "C", w: "w-[82px]",pos: "right"},

  // Q row
  { text: "tab", type: "C", w: "w-[82px]",pos: "left"},
  { text: "Q", type: "A" },
  { text: "W", type: "A" },
  { text: "E", type: "A" },
  { text: "R", type: "A" },
  { text: "T", type: "A" },
  { text: "Y", type: "A" },
  { text: "U", type: "A" },
  { text: "I", type: "A" },
  { text: "O", type: "A" },
  { text: "P", type: "A" },
  { text: "[", image: "{", type: "B" },
  { text: "]", image: "}", type: "B" },
  { text: "\\", image: "|", type: "B" },

  // A row
  { text: "caps lock", type: "C", w: "w-[92px]" ,pos: "left"},
  { text: "A", type: "A" },
  { text: "S", type: "A" },
  { text: "D", type: "A" },
  { text: "F", type: "A" },
  { text: "G", type: "A" },
  { text: "H", type: "A" },
  { text: "J", type: "A" },
  { text: "K", type: "A" },
  { text: "L", type: "A" },
  { text: ";", image: ":", type: "B" },
  { text: "'", image: "\"", type: "B" },
  { text: "return", type: "C", w: "w-[94px]" ,pos: "right"},

  // Z row
  { text: "shift", type: "C", w: "w-[120px]",pos: "left"},
  { text: "Z", type: "A" },
  { text: "X", type: "A" },
  { text: "C", type: "A" },
  { text: "V", type: "A" },
  { text: "B", type: "A" },
  { text: "N", type: "A" },
  { text: "M", type: "A" },
  { text: ",", image: "<", type: "B" },
  { text: ".", image: ">", type: "B" },
  { text: "/", image: "?", type: "B" },
  { text: "shift", type: "C", w: "w-[120px]" ,pos: "right"},

  // Bottom row (with images)
  { text: "o", image: "fn", type: "D", w: "w-[50px] text-left" },
  { text: "control", image: "⌃", type: "D", w: "w-[50px]" },
  { text: "option", image: "⌥", type: "D", w: "w-[50px]" },
  { text: "command", image: "⌘", type: "D", w: "w-[66px]" },
  { text: "", image: "", type: "D", w: "w-[266px]" },
  { text: "command", image: "⌘", type: "E", w: "w-[66px]" },
  { text: "option", image: "⌥", type: "E", w: "w-[50px]" },
  { type: "arrow" },
];
